Add v-html directive to template.ts in order to render raw HTML
sant123/vuejs-uib-pagination pull request #12
Opened 2017-10-24 21:15 UTC by feload

Add v-html directive to template.ts in order to render raw HTML.

2017-10-25 15:36 UTC, sant123 requested changes
Please update package.json version for this change.

2017-10-25 15:36 UTC, sant123 commented on demo/es6/index.html
> +        <div is="uib-pagination"  :direction-links="false" :total-items="totalItems" v-model="pagination1" :page-label="pageLabelHtml"></div>
This line is a duplicate of above.

2017-10-25 18:16 UTC, feload reviewed
Ok, removed duplicate line.

2017-10-26 03:57 UTC, sant123 approved these changes

2017-10-26 03:57 UTC, merged